In [19]:
import pandas as pd

In [20]:
path = "../data/raw/openfoodfacts_sample.csv"
df = pd.read_csv(path)

C:\Users\34651\AppData\Local\Temp\ipykernel_23312\1575630588.py:2: DtypeWarning: Columns (94,95,124,205,246,272,276,310,340,359,360,361,366,368,369,370,371,377,378,381,385,390,399,402,403,405,409,410,416,417,448,450,452,453,454,455,456,457,458,459,461,465,466,471,475,476,478,479,480,483,484,485,486,487,488,489,490,491,492,493,494,495,496,499,500,508,509,511,522,523,524,525,534,537,538,539,540,541,560,561,562,563,564,565,570,581,587,589,591,592,598,600,602,611,612,614,615,619,625,626,627,632,633,634,635,636,637,640,641,642,643,644,645,646,647,648,649,650,651,656,657,658,659,660,661,662,663,667,668,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,689,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,723,724,725,726,727,728,729,730,731,732,733,734,744,745,746,747,748,749,754,755,756,758,759,760,762,764,767,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,836,837,838,839,840,841,874,875,876,877,878,879,886,887,888,889,890,891,892,893,894,895,896,897,898,900,905,906,908,909,910,911,912,913,914,915,916,917,918,919,921,922,923,924,929,932,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1026,1027,1028,1038,1039,1040,1041,1042,1043,1044,1048,1049,1050,1051,1052,1053,1054,1055,1056) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

In [9]:
# Check the name of the columns
columns = df.columns

with open("columns2.txt", "w", encoding="utf-8") as f:
    for item in columns:
        f.write(str(item) + "\n")

In [ ]:
# Select only important columns
FIELDS = [
    # Identification
    "code", "product_name", "generic_name", "quantity",
    "product_quantity", "product_quantity_unit",
    "serving_size", "lang", "url",
    # Brand
    "brands", "brands_tags", "owner",
    "manufacturing_places", "manufacturing_places_tags",
    # Category
    "categories", "categories_tags", "categories_hierarchy",
    "pnns_groups_1", "pnns_groups_2",
    "food_groups", "food_groups_tags",
    # Country
    "countries", "countries_tags", "countries_hierarchy",
    "origins", "origins_tags", "purchase_places",
    # Nutrition
    "nutriments", "nutrition_data_per",
    "nutriscore_grade", "nutriscore_score",
    "nova_group", "ecoscore_grade", "ecoscore_score",
    "nutrient_levels",
    # Ingredients
    "ingredients_text", "ingredients_n",
    "allergens_tags", "traces_tags",
    "additives_n", "additives_tags",
    "ingredients_analysis_tags", "labels", "labels_tags",
    # Packaging
    "packaging", "packaging_tags",
    "packaging_materials_tags", "packaging_recycling_tags",
    # Date and quality
    "created_t", "last_modified_t", "last_updated_t", "completeness",
    # Imgages
    "image_url", "image_front_url", "image_front_small_url",
]

df = df[FIELDS]

,code,product_name,generic_name,quantity,product_quantity,product_quantity_unit,serving_size,lang,url,brands,...,packaging_tags,packaging_materials_tags,packaging_recycling_tags,created_t,last_modified_t,last_updated_t,completeness,image_url,image_front_url,image_front_small_url
0,6111246721261,Fromage Blanc Nature,NaN,1 kg,1000.0,g,100 g,fr,https://world.openfoodfacts.org/product/611124...,Milky Food Professional,...,['en:plastic'],['en:plastic'],[],1622750466,1779273710,1779273710,0.9000,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...
1,6111035000430,Sidi Ali,NaN,33 cl,330.0,ml,1l,es,https://world.openfoodfacts.org/product/611103...,سيدي علي,...,"['en:plastic', 'en:bottle']",['en:plastic'],[],1439924914,1779352592,1779352592,0.9000,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...
2,6111242100992,Perly,NaN,100 g,100.0,g,80g,en,https://world.openfoodfacts.org/product/611124...,Jaouda,...,['en:plastic'],['en:plastic'],[],1474037086,1779347951,1779347951,1.0625,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...
3,6111035000058,Eau minérale naturelle,NaN,"1,5 L",1500.0,ml,330 ml,en,https://world.openfoodfacts.org/product/611103...,sidi ali,...,"['en:plastic', 'en:bottle-or-vial', 'en:bottle']",['en:plastic'],[],1409671459,1779391270,1779391270,1.0000,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...
4,6111035002175,Sidi Ali,NaN,2 L,2000.0,ml,NaN,fr,https://world.openfoodfacts.org/product/611103...,Sidi Ali,...,[],['en:plastic'],[],1537111522,1775998974,1775998974,0.8000,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...

In [8]:
print(len(df.columns))

55

In [10]:
# Ver las columnas object
string_cols = df.select_dtypes(include=["object"]).columns.tolist()

with open("columns_types.txt", "w", encoding="utf-8") as f:
    for col in string_cols:
        value = df[col].dropna().iloc[0]
        f.write(f"{col}: {str(value)[:200]}" "\n")

In [19]:
import ast
df2 = df[df["nutrient_levels"].notna()]
list_nutrient = df2["nutrient_levels"].apply(ast.literal_eval).tolist()
print(list_nutrient)

[{'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'salt': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'moderate'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'moderate'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'salt': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'salt': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'moderate'}, {'salt': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'high', 'saturated-fat': 'high', 'sugars': 'moderate'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'high', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'high', 'salt': 'high', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'high', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'high', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'high', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'high', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {}, {'fat': 'low', 'salt': 'high', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'high', 'salt': 'high', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'high', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'high', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'high'}, {}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'high', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'moderate'}, {'salt': 'low'}, {'fat': 'high', 'salt': 'high', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'high', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'low', 'salt': 'high', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'low', 'salt': 'high', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'high', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'high', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'high', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'high', 'saturated-fat': 'mode

In [24]:
keys = []
values = []
for element in list_nutrient:
    for key, value in element.items():
        if key not in keys:
            keys.append(key)
        if value not in values:
            values.append(value)

print(keys)
print(values)

['fat', 'salt', 'saturated-fat', 'sugars']
['moderate', 'low', 'high']

In [15]:
def parse_nutrient_levels(x):
    if x is None or x == "" or (isinstance(x, float) and pd.isna(x)):
        return None, None, None, None
    try:
        # Convert string to dict first
        if isinstance(x, str):
            d = ast.literal_eval(x)
        else:
            d = x
        return (
            d.get("fat", "unknown"),
            d.get("salt", "unknown"),
            d.get("saturated-fat", "unknown"),
            d.get("sugars", "unknown")
        )
    except Exception as e:
        print(f"Error: {e}, value: {x}")
        return None, None, None, None

In [16]:
# Extracts fat, salt, saturated_fat and sugars from nutrient_levels dict.
df[["fat_level", "salt_level", "saturated_fat_level", "sugars_level"]] = df["nutrient_levels"].apply(
    lambda x: pd.Series(parse_nutrient_levels(x))
    )

In [17]:
df[["nutrient_levels", "fat_level", "salt_level", "saturated_fat_level", "sugars_level"]].head()

,nutrient_levels,fat_level,salt_level,saturated_fat_level,sugars_level
0,"{'fat': 'moderate', 'salt': 'low', 'saturated-...",moderate,low,high,low
1,"{'fat': 'low', 'salt': 'low', 'saturated-fat':...",low,low,low,low
2,"{'fat': 'moderate', 'salt': 'low', 'saturated-...",moderate,low,low,moderate
3,"{'fat': 'low', 'salt': 'low', 'saturated-fat':...",low,low,low,low
4,{'salt': 'low'},unknown,low,unknown,unknown

In [18]:
print(parse_nutrient_levels({'fat': 'moderate', 'salt': 'low'}))
print(parse_nutrient_levels("{'fat': 'moderate', 'salt': 'low'}"))
print(parse_nutrient_levels(None))

('moderate', 'low', 'unknown', 'unknown')
('moderate', 'low', 'unknown', 'unknown')
(None, None, None, None)

In [14]:
import ast

x = "{'fat': 'moderate', 'salt': 'low'}"
print(type(x))
print(ast.literal_eval(x))

<class 'str'>
{'fat': 'moderate', 'salt': 'low'}

In [74]:
import ast
df2 = df[df["packaging_tags"].notna()]
list = df2["packaging_tags"].apply(ast.literal_eval).tolist()
elements = []

for array in list:
    for element in array:
        if element not in elements:
            elements.append(element)

len(elements)

400

In [69]:
import ast
df2 = df[df["nutriments"].notna()]
list_dicts = df2["nutriments"].apply(ast.literal_eval).tolist()
elements = set()

for d in list_dicts:
    elements.update(d.keys())

len(elements)

476

In [70]:
elements

{'added-sugars',
 'added-sugars_100g',
 'added-sugars_modifier',
 'added-sugars_serving',
 'added-sugars_unit',
 'added-sugars_value',
 'alcohol',
 'alcohol_100g',
 'alcohol_serving',
 'alcohol_unit',
 'alcohol_value',
 'alpha-linolenic-acid',
 'alpha-linolenic-acid_100g',
 'alpha-linolenic-acid_modifier',
 'alpha-linolenic-acid_serving',
 'alpha-linolenic-acid_unit',
 'alpha-linolenic-acid_value',
 'arachidic-acid',
 'arachidic-acid_100g',
 'arachidic-acid_serving',
 'arachidic-acid_unit',
 'arachidic-acid_value',
 'arachidonic-acid',
 'arachidonic-acid_100g',
 'arachidonic-acid_serving',
 'arachidonic-acid_unit',
 'arachidonic-acid_value',
 'beta-carotene',
 'beta-carotene_100g',
 'beta-carotene_serving',
 'beta-carotene_unit',
 'beta-carotene_value',
 'beta-glucan',
 'beta-glucan_100g',
 'beta-glucan_serving',
 'beta-glucan_unit',
 'beta-glucan_value',
 'bicarbonate',
 'bicarbonate_100g',
 'bicarbonate_serving',
 'bicarbonate_unit',
 'bicarbonate_value',
 'biotin',
 'biotin_100g',
 'biotin_serving',
 'biotin_unit',
 'biotin_value',
 'caffeine',
 'caffeine_100g',
 'caffeine_serving',
 'caffeine_unit',
 'caffeine_value',
 'calcium',
 'calcium_100g',
 'calcium_modifier',
 'calcium_prepared',
 'calcium_prepared_100g',
 'calcium_prepared_serving',
 'calcium_prepared_value',
 'calcium_serving',
 'calcium_unit',
 'calcium_value',
 'carbohydrates',
 'carbohydrates-total',
 'carbohydrates-total_100g',
 'carbohydrates-total_serving',
 'carbohydrates-total_unit',
 'carbohydrates-total_value',
 'carbohydrates_100g',
 'carbohydrates_modifier',
 'carbohydrates_prepared',
 'carbohydrates_prepared_100g',
 'carbohydrates_prepared_serving',
 'carbohydrates_prepared_value',
 'carbohydrates_serving',
 'carbohydrates_unit',
 'carbohydrates_value',
 'carbon-footprint',
 'carbon-footprint_100g',
 'carbon-footprint_serving',
 'carbon-footprint_unit',
 'carbon-footprint_value',
 'chloride',
 'chloride_100g',
 'chloride_serving',
 'chloride_unit',
 'chloride_value',
 'cholesterol',
 'cholesterol_100g',
 'cholesterol_modifier',
 'cholesterol_serving',
 'cholesterol_unit',
 'cholesterol_value',
 'choline',
 'choline_100g',
 'choline_serving',
 'choline_unit',
 'choline_value',
 'chromium',
 'chromium_100g',
 'chromium_serving',
 'chromium_unit',
 'chromium_value',
 'cocoa',
 'cocoa_100g',
 'cocoa_serving',
 'cocoa_unit',
 'cocoa_value',
 'copper',
 'copper_100g',
 'copper_serving',
 'copper_unit',
 'copper_value',
 'energy',
 'energy-kcal',
 'energy-kcal_100g',
 'energy-kcal_modifier',
 'energy-kcal_prepared',
 'energy-kcal_prepared_100g',
 'energy-kcal_prepared_serving',
 'energy-kcal_prepared_value',
 'energy-kcal_serving',
 'energy-kcal_unit',
 'energy-kcal_value',
 'energy-kj',
 'energy-kj_100g',
 'energy-kj_modifier',
 'energy-kj_prepared',
 'energy-kj_prepared_100g',
 'energy-kj_prepared_modifier',
 'energy-kj_prepared_serving',
 'energy-kj_prepared_value',
 'energy-kj_serving',
 'energy-kj_unit',
 'energy-kj_value',
 'energy_100g',
 'energy_modifier',
 'energy_prepared',
 'energy_prepared_100g',
 'energy_prepared_modifier',
 'energy_prepared_serving',
 'energy_prepared_value',
 'energy_serving',
 'energy_unit',
 'energy_value',
 'fat',
 'fat_100g',
 'fat_modifier',
 'fat_prepared',
 'fat_prepared_100g',
 'fat_prepared_modifier',
 'fat_prepared_serving',
 'fat_prepared_value',
 'fat_serving',
 'fat_unit',
 'fat_value',
 'fiber',
 'fiber_100g',
 'fiber_modifier',
 'fiber_prepared',
 'fiber_prepared_100g',
 'fiber_prepared_modifier',
 'fiber_prepared_serving',
 'fiber_prepared_value',
 'fiber_serving',
 'fiber_unit',
 'fiber_value',
 'fluoride',
 'fluoride_100g',
 'fluoride_modifier',
 'fluoride_serving',
 'fluoride_unit',
 'fluoride_value',
 'fructose',
 'fructose_100g',
 'fructose_serving',
 'fructose_unit',
 'fructose_value',
 'fruits-vegetables-legumes',
 'fruits-vegetables-legumes-estimate-from-ingredients_100g',
 'fruits-vegetables-legumes_100g',
 'fruits-vegetables-legumes_serving',
 'fruits-vegetables-legumes_unit',
 'fruits-vegetables-legumes_value',
 'fruits-vegetables-nuts',
 'fruits-vegetables-nuts-dried',
 'fruits-vegetables-nuts-dried_100g',
 'fruits-vegetables-nuts-dried_serving',
 'fruits-vegetables-nuts-dried_unit',
 'fruits-vegetables-nuts-dried_value',
 'fruits-vegetables-nuts-estimate-from-ingredients_100g',
 'fruits-vegetables-nuts_100g',
 'fruits-vegetables-nuts_serving',
 'fruits-vegetables-nuts_unit',
 'fruits-vegetables-nuts_value',
 'gamma-linolenic-acid',
 'gamma-linolenic-acid_100g',
 'gamma-linolenic-acid_serving',
 'gamma-linolenic-acid_unit',
 'gamma-linolenic-acid_value',
 'iodine',
 'iodine_100g',
 'iodine_serving',
 'iodine_unit',
 'iodine_value',
 'iron',
 'iron_100g',
 'iron_modifier',
 'iron_prepared',
 'iron_prepared_100g',
 'iron_prepared_serving',
 'iron_prepared_value',
 'iron_serving',
 'iron_unit',
 'iron_value',
 'lactose',
 'lactose_100g',
 'lactose_modifier',
 'lactose_serving',
 'lactose_unit',
 'lactose_value',
 'linoleic-acid',
 'linoleic-acid_100g',
 'linoleic-acid_serving',
 'linoleic-acid_unit',
 'linoleic-acid_value',
 'magnesium',
 'magnesium_100g',
 'magnesium_prepared',
 'magnesium_prepared_100g',
 'magnesium_prepared_serving',
 'magnesium_prepared_value',
 'magnesium_serving',
 'magnesium_unit',
 'magnesium_value',
 'maltodextrins',
 'maltodextrins_100g',
 'maltodextrins_serving',
 'maltodextrins_unit',
 'maltodextrins_value',
 'manganese',
 'manganese_100g',
 'manganese_serving',
 'manganese_unit',
 'manganese_value',
 'monounsaturated-fat',
 'monounsaturated-fat_100g',
 'monounsaturated-fat_serving',
 'monounsaturated-fat_unit',
 'monounsaturated-fat_value',
 'nitrate',
 'nitrate_100g',
 'nitrate_serving',
 'nitrate_unit',
 'nitrate_value',
 'nova-group',
 'nova-group_',
 'nova-group_100g',
 'nova-group_serving',
 'nova-group_unit',
 'nova-group_value',
 'oleic-acid',
 'oleic-acid_100g',
 'oleic-acid_serving',
 'oleic-acid_unit',
 'oleic-acid_value',
 'omega-3-fat',
 'omega-3-fat_100g',
 'omega-3-fat_serving',
 'omega-3-fat_unit',
 'omega-3-fat_value',
 'omega-6-fat',
 'omega-6-fat_100g',
 'omega-6-fat_serving',
 'omega-6-fat_unit',
 'omega-6-fat_value',
 'omega-9-fat',
 'omega-9-fat_100g',
 'omega-9-fat_unit',
 'omega-9-fat_value',
 'pantothenic-acid',
 'pantothenic-acid_100g',
 'pantothenic-acid_serving',
 'pantothenic-acid_unit',
 'pantothenic-acid_value',
 'ph',
 'ph_100g',
 'ph_modifier',
 'ph_serving',
 'ph_unit',
 'ph_value',
 'phosphorus',
 'phosphorus_100g',
 'phosphorus_prepared',
 'phosphorus_prepared_100g',
 'phosphorus_prepared_serving',
 'phosphorus_prepared_value',
 'phosphorus_serving',
 'phosphorus_unit',
 'phosphorus_value',
 'polyols',
 'polyols_100g',
 'polyols_serving',
 'polyols_unit',
 'polyols_value',
 'polyunsaturated-fat',
 'polyunsaturated-fat_100g',
 'polyunsaturated-fat_serving',
 'polyunsaturated-fat_unit',
 'polyunsaturated-fat_value',
 'potassium',
 'potassium_100g',
 'potassium_prepared',
 'potassium_prepared_100g',
 'potassium_prepared_serving',
 'potassium_prepared_value',
 'potassium_serving',
 'potassium_unit',
 'potassium_value',
 'proteins',
 'proteins_100g',
 'proteins_modifier',
 'proteins_prepared',
 'proteins_prepared_100g',
 'proteins_prepared_serving',
 'proteins_prepared_value',
 'proteins_serving',
 'proteins_unit',
 'proteins_value',
 'salt',
 'salt_100g',
 'salt_modifier',
 'salt_prepared',
 'salt_prepared_100g',
 'salt_prepared_serving',
 'salt_prepared_value',
 'salt_serving',
 'salt_unit',
 'salt_value',
 'saturated-fat',
 'saturated-fat_100g',
 'saturated-fat_modifier',
 'saturated-fat_prepared',
 'saturated-fat_prepared_100g',
 'saturated-fat_prepared_modifier',
 'saturated-fat_prepared_serving',
 'saturated-fat_prepared_value',
 'saturated-fat_serving',
 'saturated-fat_unit',
 'saturated-fat_value',
 'selenium',
 'selenium_100g',
 'selenium_serving',
 'selenium_unit',
 'selenium_value',
 'silica',
 'silica_100g',
 'silica_serving',
 'silica_unit',
 'silica_value',
 'sodium',
 'sodium_100g',
 'sodium_modifier',
 'sodium_prepared',
 'sodium_prepared_100g',
 'sodium_prepared_modifier',
 'sodium_prepared_serving',
 'sodium_prepared_value',
 'sodium_serving',
 'sodium_unit',
 'sodium_value',
 'starch',
 'starch_100g',
 'starch_serving',
 'starch_unit',
 'starch_value',
 'sugars',
 'sugars_100g',
 'sugars_modifier',
 'sugars_prepared',
 'sugars_prepared_100g',
 'sugars_prepared_serving',
 'sugars_prepared_value',
 'sugars_serving',
 'sugars_unit',
 'sugars_value',
 'sulphate',
 'sulphate_100g',
 'sulphate_serving',
 'sulphate_unit',
 'sulphate_value',
 'trans-fat',
 'trans-fat_100g',
 'trans-fat_modifier',
 'trans-fat_serving',
 'trans-fat_unit',
 'trans-fat_value',
 'vitamin-a',
 'vitamin-a_100g',
 'vitamin-a_modifier',
 'vitamin-a_serving',
 'vitamin-a_unit',
 'vitamin-a_value',
 'vitamin-b1',
 'vitamin-b12',
 'vitamin-b12_100g',
 'vitamin-b12_serving',
 'vitamin-b12_unit',
 'vitamin-b12_value',
 'vitamin-b1_100g',
 'vitamin-b1_serving',
 'vitamin-b1_unit',
 'vitamin-b1_value',
 'vitamin-b2',
 'vitamin-b2_100g',
 'vitamin-b2_serving',
 'vitamin-b2_unit',
 'vitamin-b2_value',
 'vitamin-b6',
 'vitamin-b6_100g',
 'vitamin-b6_serving',
 'vitamin-b6_unit',
 'vitamin-b6_value',
 'vitamin-b9',
 'vitamin-b9_100g',
 'vitamin-b9_serving',
 'vitamin-b9_unit',
 'vitamin-b9_value',
 'vitamin-c',
 'vitamin-c_100g',
 'vitamin-c_modifier',
 'vitamin-c_prepared',
 'vitamin-c_prepared_100g',
 'vitamin-c_prepared_serving',
 'vitamin-c_prepared_value',
 'vitamin-c_serving',
 'vitamin-c_unit',
 'vitamin-c_value',
 'vitamin-d',
 'vitamin-d_100g',
 'vitamin-d_prepared',
 'vitamin-d_prepared_100g',
 'vitamin-d_prepared_serving',
 'vitamin-d_prepared_value',
 'vitamin-d_serving',
 'vitamin-d_unit',
 'vitamin-d_value',
 'vitamin-e',
 'vitamin-e_100g',
 'vitamin-e_serving',
 'vitamin-e_unit',
 'vitamin-e_value',
 'vitamin-k',
 'vitamin-k_100g',
 'vitamin-k_serving',
 'vitamin-k_unit',
 'vitamin-k_value',
 'vitamin-pp',
 'vitamin-pp_100g',
 'vitamin-pp_serving',
 'vitamin-pp_unit',
 'vitamin-pp_value',
 'water',
 'water_100g',
 'water_serving',
 'water_unit',
 'water_value',
 'zinc',
 'zinc_100g',
 'zinc_prepared',
 'zinc_prepared_100g',
 'zinc_prepared_serving',
 'zinc_prepared_value',
 'zinc_serving',
 'zinc_unit',
 'zinc_value'}

In [79]:
def parse_nutrient_levels(x):
    if x is None or x == "" or (isinstance(x, float) and pd.isna(x)):
        return None, None, None, None
    try:
        # Convert string to dict first
        if isinstance(x, str):
            d = ast.literal_eval(x)
        else:
            d = x
        return (
            d.get("energy-kcal_100g", "unknown"),
            d.get("fat_100g", "unknown"),
            d.get("saturated-fat_100g", "unknown"),
            d.get("sugars_100g", "unknown"),
            d.get("salt_100g", "unknown"),
            d.get("proteins_100g", "unknown"),
            d.get("fiber_100g", "unknown"),
        )
    except Exception as e:
        print(f"Error: {e}, value: {x}")
        return None, None, None, None, None, None, None
    
# Extracts fat, salt, saturated_fat and sugars from nutrient_levels dict.
df[["energy-kcal_100g", "fat_100g", "saturated-fat_100g", "sugars_100g", "salt_100g", "proteins_100g", "fiber_100g"]] = df["nutriments"].apply(
    lambda x: pd.Series(parse_nutrient_levels(x))
    )

df[["energy-kcal_100g", "fat_100g", "saturated-fat_100g", "sugars_100g", "salt_100g", "proteins_100g", "fiber_100g"]].head()

,energy-kcal_100g,fat_100g,saturated-fat_100g,sugars_100g,salt_100g,proteins_100g,fiber_100g
0,159.0,11.0,7.15,4.0,0.1,5.0,0.0
1,0.0,0.0,0.0,1.4,0.0,0.0,0.0
2,97.0,3.0,0.0,9.4,0.0,8.0,0.0
3,0,0,unknown,unknown,0.006,0,unknown
4,unknown,unknown,unknown,unknown,0.065,unknown,unknown

In [80]:
df[df["fat_100g"] != "unknown"].head()

,code,product_name,generic_name,quantity,product_quantity,product_quantity_unit,serving_size,lang,url,brands,...,image_front_url,image_front_small_url,energy-kcal_100g,fat_100g,saturated-fat_100g,sugars_100g,salt_100g,proteins_100g,fiber_100g,fat_100g
0,6111246721261,Fromage Blanc Nature,NaN,1 kg,1000.0,g,100 g,fr,https://world.openfoodfacts.org/product/611124...,Milky Food Professional,...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,159.0,unknown,7.15,4.0,0.1,5.0,0.0,11.0
1,6111035000430,Sidi Ali,NaN,33 cl,330.0,ml,1l,es,https://world.openfoodfacts.org/product/611103...,سيدي علي,...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,0.0,unknown,0.0,1.4,0.0,0.0,0.0,0.0
2,6111242100992,Perly,NaN,100 g,100.0,g,80g,en,https://world.openfoodfacts.org/product/611124...,Jaouda,...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,97.0,unknown,0.0,9.4,0.0,8.0,0.0,3.0
3,6111035000058,Eau minérale naturelle,NaN,"1,5 L",1500.0,ml,330 ml,en,https://world.openfoodfacts.org/product/611103...,sidi ali,...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,0,unknown,unknown,unknown,0.006,0,unknown,0
5,6111266962187,Lait,NaN,450 ml,450.0,ml,NaN,fr,https://world.openfoodfacts.org/product/611126...,Jaouda,...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,45,unknown,1,0,0.225,3.1,unknown,1.5