In [1]:
import pandas as pd

In [2]:
path = "../data/raw/openfoodfacts_sample.csv"
df = pd.read_csv(path)
df.head()

C:\Users\34651\AppData\Local\Temp\ipykernel_23312\1434163817.py:2: DtypeWarning: Columns (94,95,124,205,246,272,276,310,340,359,360,361,366,368,369,370,371,377,378,381,385,390,399,402,403,405,409,410,416,417,448,450,452,453,454,455,456,457,458,459,461,465,466,471,475,476,478,479,480,483,484,485,486,487,488,489,490,491,492,493,494,495,496,499,500,508,509,511,522,523,524,525,534,537,538,539,540,541,560,561,562,563,564,565,570,581,587,589,591,592,598,600,602,611,612,614,615,619,625,626,627,632,633,634,635,636,637,640,641,642,643,644,645,646,647,648,649,650,651,656,657,658,659,660,661,662,663,667,668,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,689,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,723,724,725,726,727,728,729,730,731,732,733,734,744,745,746,747,748,749,754,755,756,758,759,760,762,764,767,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,836,837,838,839,840,841,874,875,876,877,878,879,886,887,888,889,890,891,892,893,894,895,896,897,898,900,905,906,908,909,910,911,912,913,914,915,916,917,918,919,921,922,923,924,929,932,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1026,1027,1028,1038,1039,1040,1041,1042,1043,1044,1048,1049,1050,1051,1052,1053,1054,1055,1056) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

,_id,_keywords,added_countries_tags,additives_n,additives_original_tags,additives_tags,allergens,allergens_from_ingredients,allergens_from_user,allergens_hierarchy,...,ingredients_text_fr_ocr_1546528802,ingredients_text_fr_ocr_1546528802_result,generic_name_bs,ingredients_text_bs,ingredients_text_fr_ocr_1693687034,ingredients_text_fr_ocr_1693687034_result,ingredients_text_with_allergens_bs,origin_bs,packaging_text_bs,product_name_bs
0,6111246721261,"['blanc', 'dessert', 'et', 'fermente', 'food',...",[],1.0,['en:e202'],['en:e202'],en:milk,"en:milk, Ferment lactique",(fr) en:milk,['en:milk'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6111035000430,"['ali', 'and', 'beverage', 'mineral', 'natural...",[],0.0,[],[],NaN,NaN,(en),[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6111242100992,"['creme', 'dessert', 'fermente', 'jaouda', 'la...",[],0.0,[],[],"en:banana,en:milk","en:milk, en:milk, cream, banana","(fr) en:banana,en:milk","['en:banana', 'en:milk']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6111035000058,"['14001', '22000', '45001', '9001', 'ali', 'an...",[],0.0,[],[],NaN,NaN,(en),[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6111035002175,"['ali', 'and', 'bassin', 'beverage', 'cherif',...",[],0.0,[],[],NaN,NaN,(en),[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Check the name of the columns
columns = df.columns

with open("columns2.txt", "w", encoding="utf-8") as f:
    for item in columns:
        f.write(str(item) + "\n")

In [3]:
# Select only important columns
FIELDS = [
    # Identification
    "code", "product_name", "generic_name", "quantity",
    "product_quantity", "product_quantity_unit",
    "serving_size", "lang", "url",
    # Brand
    "brands", "brands_tags", "owner",
    "manufacturing_places", "manufacturing_places_tags",
    # Category
    "categories", "categories_tags", "categories_hierarchy",
    "pnns_groups_1", "pnns_groups_2",
    "food_groups", "food_groups_tags",
    # Country
    "countries", "countries_tags", "countries_hierarchy",
    "origins", "origins_tags", "purchase_places",
    # Nutrition
    "nutriments", "nutrition_data_per",
    "nutriscore_grade", "nutriscore_score",
    "nova_group", "ecoscore_grade", "ecoscore_score",
    "nutrient_levels",
    # Ingredients
    "ingredients_text", "ingredients_n",
    "allergens_tags", "traces_tags",
    "additives_n", "additives_tags",
    "ingredients_analysis_tags", "labels", "labels_tags",
    # Packaging
    "packaging", "packaging_tags",
    "packaging_materials_tags", "packaging_recycling_tags",
    # Date and quality
    "created_t", "last_modified_t", "last_updated_t", "completeness",
    # Imgages
    "image_url", "image_front_url", "image_front_small_url",
]

df = df[FIELDS]

df.head()

,code,product_name,generic_name,quantity,product_quantity,product_quantity_unit,serving_size,lang,url,brands,...,packaging_tags,packaging_materials_tags,packaging_recycling_tags,created_t,last_modified_t,last_updated_t,completeness,image_url,image_front_url,image_front_small_url
0,6111246721261,Fromage Blanc Nature,NaN,1 kg,1000.0,g,100 g,fr,https://world.openfoodfacts.org/product/611124...,Milky Food Professional,...,['en:plastic'],['en:plastic'],[],1622750466,1779273710,1779273710,0.9000,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...
1,6111035000430,Sidi Ali,NaN,33 cl,330.0,ml,1l,es,https://world.openfoodfacts.org/product/611103...,سيدي علي,...,"['en:plastic', 'en:bottle']",['en:plastic'],[],1439924914,1779352592,1779352592,0.9000,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...
2,6111242100992,Perly,NaN,100 g,100.0,g,80g,en,https://world.openfoodfacts.org/product/611124...,Jaouda,...,['en:plastic'],['en:plastic'],[],1474037086,1779347951,1779347951,1.0625,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...
3,6111035000058,Eau minérale naturelle,NaN,"1,5 L",1500.0,ml,330 ml,en,https://world.openfoodfacts.org/product/611103...,sidi ali,...,"['en:plastic', 'en:bottle-or-vial', 'en:bottle']",['en:plastic'],[],1409671459,1779391270,1779391270,1.0000,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...
4,6111035002175,Sidi Ali,NaN,2 L,2000.0,ml,NaN,fr,https://world.openfoodfacts.org/product/611103...,Sidi Ali,...,[],['en:plastic'],[],1537111522,1775998974,1775998974,0.8000,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...

In [8]:
print(len(df.columns))

55

In [10]:
# Ver las columnas object
string_cols = df.select_dtypes(include=["object"]).columns.tolist()

with open("columns_types.txt", "w", encoding="utf-8") as f:
    for col in string_cols:
        value = df[col].dropna().iloc[0]
        f.write(f"{col}: {str(value)[:200]}" "\n")

In [19]:
import ast
df2 = df[df["nutrient_levels"].notna()]
list_nutrient = df2["nutrient_levels"].apply(ast.literal_eval).tolist()
print(list_nutrient)

[{'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'salt': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'moderate'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'moderate'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'salt': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'salt': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'moderate'}, {'salt': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'high', 'saturated-fat': 'high', 'sugars': 'moderate'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'high', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'high', 'salt': 'high', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'high', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'high', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'high', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'high', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {}, {'fat': 'low', 'salt': 'high', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'high', 'salt': 'high', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'high', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'high', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'high'}, {}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'high', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'moderate'}, {'salt': 'low'}, {'fat': 'high', 'salt': 'high', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'high', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'low', 'salt': 'high', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'low', 'salt': 'high', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'high', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'high', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'high', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'moderate', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'moderate', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'high'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'low', 'saturated-fat': 'high', 'sugars': 'high'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'moderate', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'low', 'salt': 'low', 'saturated-fat': 'low', 'sugars': 'moderate'}, {'fat': 'moderate', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {'fat': 'low', 'salt': 'moderate', 'saturated-fat': 'low', 'sugars': 'low'}, {}, {'fat': 'high', 'salt': 'moderate', 'saturated-fat': 'high', 'sugars': 'low'}, {'fat': 'moderate', 'salt': 'high', 'saturated-fat': 'mode

In [24]:
keys = []
values = []
for element in list_nutrient:
    for key, value in element.items():
        if key not in keys:
            keys.append(key)
        if value not in values:
            values.append(value)

print(keys)
print(values)

['fat', 'salt', 'saturated-fat', 'sugars']
['moderate', 'low', 'high']

In [15]:
def parse_nutrient_levels(x):
    if x is None or x == "" or (isinstance(x, float) and pd.isna(x)):
        return None, None, None, None
    try:
        # Convert string to dict first
        if isinstance(x, str):
            d = ast.literal_eval(x)
        else:
            d = x
        return (
            d.get("fat", "unknown"),
            d.get("salt", "unknown"),
            d.get("saturated-fat", "unknown"),
            d.get("sugars", "unknown")
        )
    except Exception as e:
        print(f"Error: {e}, value: {x}")
        return None, None, None, None

In [16]:
# Extracts fat, salt, saturated_fat and sugars from nutrient_levels dict.
df[["fat_level", "salt_level", "saturated_fat_level", "sugars_level"]] = df["nutrient_levels"].apply(
    lambda x: pd.Series(parse_nutrient_levels(x))
    )

In [17]:
df[["nutrient_levels", "fat_level", "salt_level", "saturated_fat_level", "sugars_level"]].head()

,nutrient_levels,fat_level,salt_level,saturated_fat_level,sugars_level
0,"{'fat': 'moderate', 'salt': 'low', 'saturated-...",moderate,low,high,low
1,"{'fat': 'low', 'salt': 'low', 'saturated-fat':...",low,low,low,low
2,"{'fat': 'moderate', 'salt': 'low', 'saturated-...",moderate,low,low,moderate
3,"{'fat': 'low', 'salt': 'low', 'saturated-fat':...",low,low,low,low
4,{'salt': 'low'},unknown,low,unknown,unknown

In [18]:
print(parse_nutrient_levels({'fat': 'moderate', 'salt': 'low'}))
print(parse_nutrient_levels("{'fat': 'moderate', 'salt': 'low'}"))
print(parse_nutrient_levels(None))

('moderate', 'low', 'unknown', 'unknown')
('moderate', 'low', 'unknown', 'unknown')
(None, None, None, None)

In [14]:
import ast

x = "{'fat': 'moderate', 'salt': 'low'}"
print(type(x))
print(ast.literal_eval(x))

<class 'str'>
{'fat': 'moderate', 'salt': 'low'}